### ISSUE TITLE
`sed: illegal option -- r` in MacOS

### ISSUE THREAD

**Issue by Jeckerson** [shivammathur/setup-php#680] opened 2022-12-26 20:35 UTC
**Describe the bug**
MacOS runs failing.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
MacOS

**PHP versions**
Any

**To Reproduce**
https://github.com/zephir-lang/zephir/actions/runs/3783117341/jobs/6431403311#step:3:28

**Comment by shivammathur** [comment] 2022-12-26 21:40
@Jeckerson 

I could not reproduce this, Please point me to the workflow where the error is, or provide me the YAML for the `setup-php` step.

https://github.com/shivammathur/test-setup-php/actions/runs/3783581421/workflow

**Comment by Jeckerson** [comment] 2022-12-26 21:42
@shivammathur https://github.com/zephir-lang/zephir/actions/runs/3783117341/jobs/6431403311#step:3:28

URL was inside comment.

**Comment by shivammathur** [comment] 2022-12-26 23:06
@Jeckerson 

I will fix that, but this error is not why your CI is failing.

`macos-10.15` is no longer supported by homebrew, Please upgrade your runner to `macos-11` or `macos-12` preferably.
Ref: https://docs.brew.sh/Installation#2

**Comment by shivammathur** [comment] 2022-12-26 23:16
Fixed in https://github.com/shivammathur/setup-php/commit/40846b27d077189fd11f58029923a4e997fcf059

**Comment by shivammathur** [comment] 2023-01-27 03:30
Released the fix in [2.24.0](https://github.com/shivammathur/setup-php/releases/tag/2.24.0)

**Closed by shivammathur** 2023-01-27 03:30 UTC
Labels: bug, awaiting-release
