### ISSUE TITLE
PHP 8.1 uses wrong php-src branch?

### ISSUE THREAD

**Issue by ondrejmirtes** [shivammathur/setup-php#527] opened 2021-11-11 10:39 UTC
**Describe the bug**

Hi, I'm experiencing a weird failure with PHP 8.1 on Ubuntu builds: https://github.com/phpstan/phpstan-src/runs/4176492148?check_suite_focus=true

I don't see how it could fail like this on PHP 8.1 on Ubuntu and pass on other versions and even on PHP 8.1 on Windows. Last time I see this method fail was when PHP 8.0 changed this (https://wiki.php.net/rfc/namespaced_names_as_token) and the code wasn't ready for that yet.

I can't reproduce this problem locally so I started investigating what's going on in GitHub Actions.

I noticed the Git commit hash used by setup-php when asked for `8.1`: 4508196cc2dda5eb86b7f4440e1ccb8cdac3d874 on Ubuntu, 4aa73bbfc4cdcc4a2478a362196c66c85daca314 on Windows.

The first commit is on master branch: https://github.com/php/php-src/commits/master
The second commit is on the correct PHP 8.1 branch: https://github.com/php/php-src/commits/PHP-8.1

So something weird is definitely going on. I just hope I'm not wasting your time cause someone push the wrong branch and then covered their tracks with a force-push...

**Version**
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
Ubuntu

**PHP versions**
8.1

**Comment by shivammathur** [comment] 2021-11-11 13:13
The branches used to build PHP were correct, the part which saved the commit hash in the build was wrong.

This is fixed in https://github.com/shivammathur/php-builder/commit/00ff61c89be311333a4ebb507900673bb485c6fc and new builds are complete.

**Closed by shivammathur** 2021-11-11 13:13 UTC
Labels: bug

**Comment by ondrejmirtes** [comment] 2021-11-17 16:11
I've tracked the problem down but I don't know whose problem it is: https://bugs.php.net/bug.php?id=81632

**Comment by shivammathur** [comment] 2021-11-18 05:48
@ondrejmirtes 

The issue is in `php8.1-ds` package from `ppa:ondrej/php`.

It works correctly when testing with the master branch of `ds`.
```yml
extensions: ds-php-ds/ext-ds@master, mbstring`
```

So, I have added `ds` from the `master` branch of the extension to the builds in https://github.com/shivammathur/php-builder/commit/e6abaeb0e277a85a0d19e387aed663d3d080d7d9.

It should correctly tokenize now. Please test and let me know.
Test workflow (after fix): https://github.com/shivammathur/test-setup-php/runs/4247525223?check_suite_focus=true#step:6:1

**Comment by ondrejmirtes** [comment] 2021-11-18 07:13
Awesome, thank you very much!

Can you please report the problem to https://github.com/oerdnj/deb.sury.org so that people don't bump into the same issue later this month?
