### ISSUE TITLE
PHP 8: type casting goes wrong

### ISSUE THREAD

**Issue by Slamdunk** [shivammathur/setup-php#342] opened 2020-11-23 08:24 UTC
### Code

```php
$firstRowColumns  = 63;

var_dump([
    $firstRowColumns,
    ($firstRowColumns / 120),
    ($firstRowColumns / 120 * 100),
    (int) ($firstRowColumns / 120 * 100),
]);
```

### Expected vs Actual diff

```diff
 array(4) {
   [0]=>
   int(63)
   [1]=>
   float(0.525)
   [2]=>
   float(52.5)
   [3]=>
-  int(52)
+  int(0)
 }
```

### References

1. https://github.com/paratestphp/paratest/pull/563/files#diff-518dd652a8ace65caa1464638902d9b7c742f85b4cd4f0549c66c74a21057386
1. https://github.com/paratestphp/paratest/pull/563/checks#step:11:14
1. https://3v4l.org/kkRIE

I have no idea what's going on :\

**Comment by shivammathur** [comment] 2020-11-23 09:35
@Slamdunk
The issue is `opcache`. When it kicks in on `PHP 8.0`, the evaluation is wrong
https://github.com/shivammathur/test-setup-php/runs/1441234134?check_suite_focus=true#step:4:115

Can you file a bug report about on [php bug tracker](https://bugs.php.net)

**Comment by Slamdunk** [comment] 2020-11-23 09:43
Locally works fine, with docker:

```
$ docker run --rm php:rc-cli php -dopcache.enable=1 -i | head -n 5
phpinfo()
PHP Version => 8.0.0RC3

System => Linux ae079ef5dac4 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64
Build Date => Nov  5 2020 19:23:54

$ docker run --rm php:rc-cli php -dopcache.enable=1 -r 'var_dump((int) (63 / 120 * 100));'
int(52)
```

So I'm not able to provide bugs.php.net the necessary details to reproduce it.

May you help me?

**Comment by renanbr** [comment] 2020-11-23 09:59
I cannot reproduce locally either with `ppa:ondrej/php` build

---

```
cat casting.php 
```

```
<?php

$firstRowColumns  = 63;

var_dump([
    $firstRowColumns,
    ($firstRowColumns / 120),
    ($firstRowColumns / 120 * 100),
    (int) ($firstRowColumns / 120 * 100),
]);
```

---


```
php8.0 --version
```

```
PHP 8.0.0RC3 (cli) (built: Oct 31 2020 17:06:57) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.0RC3, Copyright (c), by Zend Technologies
    with Xdebug v3.0.0beta1, Copyright (c) 2002-2020, by Derick Rethans
```

---

```
php8.0 -f casting.php 
```

```
/tmp/casting.php:9:
array(4) {
  [0] =>
  int(63)
  [1] =>
  double(0.525)
  [2] =>
  double(52.5)
  [3] =>
  int(52)
}
```

**Comment by shivammathur** [comment] 2020-11-23 10:09
The build on GitHub Actions is most recent from PHP-8.0.0 branch.
The docker and `ppa:ondrej/php` builds are older.
Also you need to run it with opcache enabled multiple times till it kicks in to test.

Reported - https://bugs.php.net/bug.php?id=80404

**Comment by shivammathur** [comment] 2020-11-23 10:16
Till this is fixed you can set `opcache.enable=0` in ini-values input.
Lets see what the response is, if there is no fix before GA which is likely, I will disable opcache by default until this is fixed in `PHP 8.0`.

**Comment by shivammathur** [comment] 2020-11-24 04:20
@Slamdunk 
`opcache` and `JIT` is disabled by default from now in PHP 8.0+ on setup-php, so this error will not occur and your workflows should successfully complete.
I will close this and document JIT configuration better in next release.

**Closed by shivammathur** 2020-11-24 04:20 UTC
Labels: bug

**Comment by T2L** [comment] 2020-11-24 22:23
Seems like the issue with opcache has been fixed already and it's included in PHP8.0!
