### ISSUE TITLE
Ini handling broken when passed via output parameter

### ISSUE THREAD

**Issue by jrfnl** [shivammathur/setup-php#405] opened 2021-02-04 05:42 UTC
First, let me please thank you for this action! I think it's awesome and very much appreciate all the work on it!

**Describe the bug**
I think this is related to the fix which was committed in response to issue #392.

#### Short version:
Setting ini parameters in a separate step and passing them to the `setup-php` action using `step.stepid.outputs.outputname` no longer works.

#### Long version:

For a project which has to support a large number of PHP versions as well as a large range of versions for a "framework", some PHP/framework combinations will generate PHP deprecation notices.
These do not break the actual product, but do cause a lot of noise in the output of the unit tests, so when running the tests via GH Actions against older versions of the "framework", `error_reporting` is set to `E_ALL & ~E_DEPRECATED`, while when testing against the current version of the framework, it is set to `E_ALL`.

As this needs some logic, the `ini-value` string is created in a separate step and [saved as an output parameter](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter). This output parameter is subsequently used in the next step to call `setup-php`.

This was working fine until about a month ago ([last good run](https://github.com/PHPCompatibility/PHPCompatibility/actions/runs/449702540)), but started to fail about [three weeks ago](https://github.com/PHPCompatibility/PHPCompatibility/actions/runs/492177501).

The failing tests were all of the `Failed asserting that exception of type "PHPUnit\Framework\Error\Warning" is thrown.` kind and could not be reproduced locally, no matter what PHP/framework/PHPUnit combinations were used.

After various test runs and debug trial & error, I can only conclude that it is related to how the `ini-values` are handled by the `setup-php` action.

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**
- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
PHP 5.4 up to 8.1

**To Reproduce**

This is the relevant part of the script:
```yml
      - name: Setup ini config
        id: set_ini
        run: |
          # On stable PHPCS versions, allow for PHP deprecation notices.
          # Unit tests don't need to fail on those for stable releases where those issues won't get fixed anymore.
          # Also set the "short_open_tag" ini to make sure specific conditions are tested.
          if [ ${{ matrix.custom_ini }} == "true" ]; then
            if [ "${{ matrix.phpcs_version }}" != "dev-master" ]; then
              echo '::set-output name=PHP_INI::error_reporting=E_ALL & ~E_DEPRECATED, short_open_tag=On'
            else
              echo '::set-output name=PHP_INI::error_reporting=E_ALL, short_open_tag=On'
            fi
          else
            if [ "${{ matrix.phpcs_version }}" != "dev-master" ]; then
              echo '::set-output name=PHP_INI::error_reporting=E_ALL & ~E_DEPRECATED'
            else
              echo '::set-output name=PHP_INI::error_reporting=E_ALL'
            fi
          fi

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: ${{ steps.set_ini.outputs.PHP_INI }}
          coverage: none
```

The full script can be found here: https://github.com/PHPCompatibility/PHPCompatibility/blob/43b2b058b7875b249661ce23c62402c72067fa64/.github/workflows/test.yml

**Expected behavior**
That the ini-values are handled correctly, allowing for the tests to pass.

**Screenshots/Logs**
See links above in the description for relevant action logs.

**Are you willing to submit a PR?**
Would love to, but have too much on my plate right now and the hours spend trying to figure out what was going wrong here didn't help.... 😒

**Comment by shivammathur** [comment] 2021-02-04 08:18
@jrfnl 
Sorry about this, I missed accounting for error constants. It should not quote them now.
Fixed in https://github.com/shivammathur/setup-php/commit/1686147b24d176ca416781e2af1576dc3ed05ef0

Let me know if the issue is still there.

**Comment by jrfnl** [comment] 2021-02-04 08:21
@shivammathur Thanks for this really quick turn-around on the issue! I'll start a build on our default branch now to confirm the fix.

**Comment by jrfnl** [comment] 2021-02-04 08:38
The builds are turning green again. Fix confirmed. Thanks so much!

**Closed** 2021-02-04 08:38 UTC
Labels: bug
