### ISSUE TITLE
Ioncube doesn't install on php 7.2

### ISSUE THREAD

**Issue by jocel1** [shivammathur/setup-php#856] opened 2024-07-02 10:06 UTC
**Describe the bug**
Since the latest bumpup of the v2 tag, ioncube doesn't install anymore on v2
When using 2.29.0 release everything works properly
**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`

**Runners**

- [x] GitHub Hosted

**Operating systems**
ubuntu-latest

**PHP versions**
7.2

**To Reproduce**
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: intl, mbstring, gd, apcu, memcached, ioncube
          coverage: xdebug

**Expected behavior**
Properly install ioncube

**Screenshots/Logs**
<img width="710" alt="image" src="https://github.com/shivammathur/setup-php/assets/1429072/93e10c4b-dda3-435d-93dd-23e8302b3146">

2.29.0:

<img width="735" alt="image" src="https://github.com/shivammathur/setup-php/assets/1429072/d9e86c3a-3940-4a8a-bf1e-93decd87cc22">

**Comment by shivammathur** [comment] 2024-07-02 10:54
@jocel1 
Please try running the workflow again, I'm unable to reproduce the issue
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/9759633744/job/26936713788#step:2:19

**Comment by jocel1** [comment] 2024-07-02 11:24
Same issue after several retry. I'm also using cache-extensions module, I'll try without it:

  code-quality:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2']
    env:
      extensions: intl, mbstring, gd, apcu, memcached, ioncube
      key: cache-v1
    name: Code Quality on PHP ${{ matrix.php-versions }}
    permissions:
      contents: 'read'
      id-token: 'write'

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          coverage: xdebug

**Comment by jocel1** [comment] 2024-07-02 11:28
I confirm the issue comes from the caching

**Comment by jocel1** [comment] 2024-07-02 11:39
Note caching and 2.29.0 works properly

**Comment by jocel1** [comment] 2024-07-02 11:46
2.30.4:
<img width="962" alt="image" src="https://github.com/shivammathur/setup-php/assets/1429072/a3fe2bc3-3ec9-4ed3-aee2-59c7c2d967b9">

2.30.5:
<img width="1495" alt="image" src="https://github.com/shivammathur/setup-php/assets/1429072/e4b0766c-e352-47ee-afec-7ee7794ae9a4">

**Comment by shivammathur** [comment] 2024-07-02 12:36
Ah!, Fixed in https://github.com/shivammathur/setup-php/commit/afff805ea318c148735d2a1e88142d355311db2f. It will be in the next release.

**Comment by shivammathur** [comment] 2024-07-09 15:52
Released [`2.31.1`](https://github.com/shivammathur/setup-php/releases/tag/2.31.1) with the fix.

**Closed by shivammathur** 2024-07-09 15:52 UTC
Labels: bug, awaiting-release
