### ISSUE TITLE
The process 'pwsh' failed with exit code 1

### ISSUE THREAD

**Issue by leofeyer** [shivammathur/setup-php#88] opened 2019-11-27 12:08 UTC
**Describe the bug**

Installation on Windows fails since today with the following error message: The checksum of the downloaded CA certificates is wrong!

**To reproduce**

```yml
on: push

jobs:
    main:
        runs-on: windows-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: 7.3
                  extension-csv: dom, filter, gd, hash, intl, json, pcre, pdo, zlib
                  coverage: none
```

**Log**

```
Run shivammathur/setup-php@master
pwsh C:\hostedtoolcache\windows\win32.ps1 -version 7.3 -dir d:\a\_actions\shivammathur\setup-php\master\dist

==> Setup PhpManager 
√ PhpManager Installed 

==> Setup PHP and Composer 
The checksum of the downloaded CA certificates is wrong!
At C:\Users\runneradmin\Documents\PowerShell\Modules\PhpManager\1.19.2.231\private\Get-CACertFromCurl.ps1:35 char:13
+             throw "The checksum of the downloaded CA certificates is  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (The checksum of the\u2026tificates is wrong!:String) [], RuntimeException
+ FullyQualifiedErrorId : The checksum of the downloaded CA certificates is wrong!

##[error]The process 'pwsh' failed with exit code 1
##[error]Node run failed with exit code 1
```

**Additional information**

https://github.com/leofeyer/gha-test/commit/b9c59a05a74bf5bc1632b69eb87891094054d187/checks?check_suite_id=331319247

**Comment by shivammathur** [comment] 2019-11-27 14:34
@mlocati Can you please check this.

**Comment by shivammathur** [comment] 2019-11-27 15:38
@leofeyer PHP installation will not fail now. Fixed in #89.
Will close this once the actual bug in `Update-PhpCAInfo` is fixed.

**Comment by leofeyer** [comment] 2019-11-27 15:42
Thank you again 🙏

**Comment by mlocati** [comment] 2019-11-27 16:04
>     * Fix `Update-PhpCAInfo` in [PhpManager](https://github.com/mlocati/powershell-phpmanager). @mlocati Can you please check this.

Well, yes, your fix will avoid the reported issue, but PHP won't be able to perform HTTPS web requests.
That's because PHP doesn't know a list of reliable Certification Authorities (that's not the case on Mac/Linux since on those systems PHP reads the system CA list).

The problem is pretty ugly:
1. PhpManager first tries to fetch the list of reliable CAs from the Windows registry ([see here](https://github.com/shivammathur/setup-php/blob/1.5.5/src/scripts/win32.ps1#L50))
2. If the script is executed in PowerShell Core, the `PKI` powershell system module isn't available, so PhpManager won't find the `Export-Certificate` function, and it will fail (that's why we need [this try/catch](https://github.com/shivammathur/setup-php/blob/1.5.5/src/scripts/win32.ps1#L49-L52)
3. If fetching the certificates from Windows fails, we'll use the CA list [from curl](https://curl.haxx.se/docs/caextract.html).
BTW, when the people at curl update the CA list, there's a range of time when their CA list file and their checksum is wrong: I wrote them about this issue about 1 year ago, and here's their answer:
    
    >> I downloaded the file https://curl.haxx.se/ca/cacert.pem.sha256 and it
    >> contains this hash: 
    > 238823cd92d3bcdd67c1c278536d6c282dd6b526ee6ee97efbf00ef31d8c5d79
    >>
    >> BTW, the hash of https://curl.haxx.se/ca/cacert.pem should be
    >> 86695B1BE9225C3CF882D283F05C944E3AABBC1DF6428A4424269A93E997DC65
    >
    > Hm, yes. Thanks for reporting this. This mismatch happens because the CA
    > bundle was updated ~8 hours ago and those files are cached by the CDN
    > frontends for 12 hours by default... I'll see what I should do about it!

I think that the solution would be to add a flag to the `Update-PhpCAInfo` command to skip checking the checksum...

**Comment by shivammathur** [comment] 2019-11-27 16:20
@mlocati 
Yes, I found the email you wrote to them https://curl.haxx.se/mail/archive-2018-10/0013.html

> I think that the solution would be to add a flag to the Update-PhpCAInfo command to skip checking the checksum

As it is a caching issue on `cURL` CDN, Adding a flag to skip the check is a good solution.

**Comment by mlocati** [comment] 2019-11-27 16:49
[Done](https://github.com/mlocati/powershell-phpmanager/commit/17109a07157957143f6be60a1190b27f78b962cf): since version 1.20.0.235, the `Update-PhpCAInfo` command supports a `-SkipChecksumCheck` flag.
So, I'd write

```PowerShell
try {
  Update-PhpCAInfo -Path $php_dir -Source CurrentUser
}
catch {
  Update-PhpCAInfo -Path $php_dir -Source Curl -SkipChecksumCheck
}
```

**Comment by shivammathur** [comment] 2019-11-27 17:38
@mlocati Thanks for the quick update. Adding this.

**Comment by shivammathur** [comment] 2019-11-27 18:26
Fixed in #90

**Closed** 2019-11-27 18:26 UTC
Labels: bug

**Comment by mlocati** [comment] 2019-11-28 14:47
Just a side note: since PhpManager version 1.20.1, the `Update-PhpCAInfo -Source CurrentUser` (and `Update-PhpCAInfo -Source LocalMachine`) command will work on PowerShell Core too (I removed a dependency from the PKI system module that's only available in PowerShell and not in PowerShell Core).
So the original `Update-PhpCAInfo -Path $php_dir -Source CurrentUser` should be enough now, we don't need the try/catch anymore.

**Comment by shivammathur** [comment] 2019-11-28 15:05
so
```pwsh
try {
  Update-PhpCAInfo -Path $php_dir -Source CurrentUser
}
catch {
  try {
    Update-PhpCAInfo -Path $php_dir -Source Curl
  } catch {
    Update-PhpCAInfo -Path $php_dir -Source Curl -SkipChecksumCheck
  }
}
```
can be replaced by
```pwsh
try {
  Update-PhpCAInfo -Path $php_dir -Source CurrentUser
} catch { }
```

**Comment by mlocati** [comment] 2019-11-28 15:07
Or simply to

```powershell
Update-PhpCAInfo -Path $php_dir -Source CurrentUser
```

**Comment by shivammathur** [comment] 2019-11-28 15:16
ok. Will change this in the next release.
