### ISSUE TITLE
phpize error

### ISSUE THREAD

**Issue by heyanlong** [shivammathur/setup-php#324] opened 2020-10-31 08:54 UTC
**Describe the bug**
```
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
/usr/bin/m4:aclocal.m4:20325: ERROR: end of file in string
autom4te: /usr/bin/m4 failed with exit status: 1
```

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

ubuntu 18.04

**PHP versions**

php 7.0 7.1 7.2
**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

Suspected to be the bug here
```
(cd "$builddir/build" && cat ../acinclude.m4 $LIBTOOL_FILES > ../aclocal.m4)
```

```
phpize_copy_files()
{
  test -d build || mkdir build

  (cd "$phpdir" && cp $FILES_BUILD "$builddir"/build)
  (cd "$aclocaldir" && cp $LIBTOOL_FILES "$builddir"/build)
  (cd "$phpdir" && cp $FILES "$builddir")
  (cd "$builddir/build" && cat ../acinclude.m4 $LIBTOOL_FILES > ../aclocal.m4)
}
```

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment] 2020-10-31 10:21
@heyanlong I have added a patch to not upgrade to yesterday's releases when installing `php-dev`. You can use `ubuntu-16.04` till the upstream issue is fixed as it has pre-installed older releases of PHP.

**Comment by shivammathur** [comment] 2020-10-31 13:40
@heyanlong Update: This is fixed upstream and I have updated the builds for `setup-php`. Let me know if the issue is fixed now.

**Closed** 2020-10-31 21:01 UTC
Labels: bug
