### ISSUE TITLE
Unable to use the new Symfony CLI

### ISSUE THREAD

**Issue by Kocal** [shivammathur/setup-php#568] opened 2022-02-24 16:56 UTC
**Describe the bug**

When using `tools: symfony-cli`, we can't use the command `symfony` because of a symbolic link issue:
```
==> Setup Tools
✓ composer Added composer 2.2.6
ln: failed to create symbolic link '/usr/local/bin/symfony-cli' -> '': No such file or directory
```

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

Ubuntu 20.04.3

**PHP versions**

PHP 8.0.15

**To Reproduce**

This is the step we use:
```yaml 
        - name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ env.PHP_VERSION }}
              coverage: ${{ inputs.php_coverage }}
              extensions: amqp, apcu, ctype, fileinfo, gd, iconv, imagick, intl, json, xml, mysql, redis, sockets, xml, zip, ${{ inputs.php_additional_extensions }}
              tools: symfony-cli, ${{ inputs.php_additional_tools }}
```

However I'm sure you can reproduce the issue with:

```yaml 
        - name: Install PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: 8.0
              tools: symfony-cli
```

**Expected behavior**

The `symfony` binary should be usable.

**Screenshots/Logs**

<img width="714" alt="Capture d’écran 2022-02-24 à 17 57 31" src="https://user-images.githubusercontent.com/2103975/155570993-ac4c077a-bb8c-42fc-b21a-2858650782e7.png">

**Additional context**

**Are you willing to submit a PR?**

**Comment by Kocal** [comment] 2022-02-24 17:04
Also opened the issue on Symfony CLI repository: https://github.com/symfony-cli/symfony-cli/issues/105

**Comment by shivammathur** [comment] 2022-02-24 17:23
@Kocal 
I could not reproduce the issue.
https://github.com/shivammathur/test-setup-php/runs/5322510677?check_suite_focus=true

Try restarting your workflow, and if it fails again try it with `shivammathur/setup@verbose` and provide me the logs.

**Comment by Kocal** [comment] 2022-02-24 17:35
Hum that's working now, maybe that was just a temporary issue, or it has been fixed upstream. 

Thanks anyway!

**Comment by shivammathur** [comment] 2022-02-24 17:37
Closing now, open reopen if this happens again

**Closed** 2022-02-24 17:37 UTC
Labels: bug
