### ISSUE TITLE
Intermittent failures fetching CA certificate bundle in Windows+WSL

### ISSUE THREAD

**Issue by asgrim** [shivammathur/setup-php#699] opened 2023-02-07 08:57 UTC
**Describe the bug**
During the execution of `shivammathur/setup-php@v2`, sometimes we get a failure:

```
 ==> Setup PHP 
✗ PHP Could not fetch CA certificate bundle from Curl 
```

Despite us having `fail-fast: true` enabled, this does not cause the job to fail, however, it does mean that some HTTPS requests later on fail (https error, because CA bundle is out of date).

The failure is intermittent, and re-running the failed jobs from GH actions will eventually turn them all green.

 * Attempt 1 - https://github.com/scoutapp/scout-apm-php/actions/runs/4111683233/attempts/1
 * ...
 * Attempt 5 - https://github.com/scoutapp/scout-apm-php/actions/runs/4111683233

Originally I thought it was a fault of #692 but that issue was closed.

I have previously tried using `shivammathur/setup-php@verbose` but there is [no additional useful output](https://github.com/scoutapp/scout-apm-php/actions/runs/4075273458/jobs/7021797172#step:5:25).

**Version**
- [x] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**
`windows-latest`, using `Vampire/setup-wsl@v2`

**PHP versions**
PHP 7.2 through to 8.2

**To Reproduce**

https://github.com/scoutapp/scout-apm-php/blob/30459215638fec79b8fb221cf1844cb75db39ba4/.github/workflows/continuous-integration.yml#L93-L130

```yaml
    steps:
      - uses: actions/checkout@v3
      - uses: Vampire/setup-wsl@v2
        if: ${{ matrix.os == 'windows-latest' }}
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ matrix.scout-ext == 'with-scout-ext' && 'zend_extension=D:\\a\\scout-apm-php\\scout-apm-php\\php_scoutapm.dll' || '' }}"
          tools: pecl, composer:v2.3
          extensions: "curl, sockets, fileinfo, ${{ matrix.extensions }}"
        env:
          fail-fast: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected behavior**

I should see:

```
==> Setup PHP 
√ PHP Installed PHP 7.2.34 
```

(replacing the PHP version with the appropriate version for each job)

**Screenshots/Logs**

![Screenshot from 2023-02-07 08-29-42](https://user-images.githubusercontent.com/496145/217192231-bcfcb0af-400d-482c-9e49-85ccf9aeaeb0.png)

**Additional context**

**Are you willing to submit a PR?**
I have no idea what the cause of the problem is, so wouldn't know where to start :(

**Comment by shivammathur** [comment] 2023-02-07 09:42
@mlocati 

Would it be possible to add some retry logic to fetching the CA bundle from curl. It fails intermittently with the following exception.
```
System.ComponentModel.Win32Exception (0x80090304): The Local Security Authority cannot be contacted
```
https://github.com/shivammathur/test-setup-php/actions/runs/4112354765/jobs/7097164119

**Comment by asgrim** [comment] 2023-02-07 09:44
@shivammathur hmm, perhaps actions/runner-images#7007 should not be closed yet, as that appears to be the same upstream issue? :thinking:

**Comment by shivammathur** [comment] 2023-02-07 10:34
@asgrim Yes, I have asked them to reopen that issue. But I'm not sure they have identified why this is happening, so adding retry logic to fetching the ca file should help.

**Comment by mlocati** [comment] 2023-02-07 13:54
> Would it be possible to add some retry logic

Should we retry the same code, let's say 3 times?

**Comment by shivammathur** [comment] 2023-02-07 14:05
@mlocati Yes, that should reduce the failures.

**Comment by mlocati** [comment] 2023-02-07 15:42
[I'm on it](https://github.com/mlocati/powershell-phpmanager/pull/107)

**Comment by mlocati** [comment] 2023-02-07 16:47
Version [1.27.0](https://github.com/mlocati/powershell-phpmanager/releases/tag/1.27.0) or PowerShell PhpManager includes this fix.

**Comment by shivammathur** [comment] 2023-02-07 17:54
@mlocati 
I don't think the retry logic is working. The exception thrown does not have ErrorCode property.
https://github.com/shivammathur/test-setup-php/actions/runs/4116709818/jobs/7107097902#step:2:14

**Comment by shivammathur** [comment] 2023-02-08 14:20
@mlocati Would it be better if it retries on any network exception instead of just this specific one?

**Comment by mlocati** [comment] 2023-02-08 15:49
Yep: see https://github.com/mlocati/powershell-phpmanager/pull/108

**Comment by shivammathur** [comment] 2023-02-08 16:50
@asgrim It should be more stable now with retries. Let me know if it still fails. 

I will close the issue for now as I'm not able to reproduce this after the fixes.
https://github.com/shivammathur/test-setup-php/actions/runs/4126330628

**Closed by shivammathur** 2023-02-08 16:50 UTC
Labels: bug

**Comment by asgrim** [comment] 2023-02-08 17:07
@shivammathur @mlocati thank you both! This is looking much better now :+1:
