### ISSUE TITLE
Symfony cli does not install anymore

### ISSUE THREAD

**Issue by starred-gijs** [shivammathur/setup-php#632] opened 2022-08-17 09:15 UTC
**Describe the bug**
When trying to install the Symfony CLI tool, it fails

**Version**
- [ ] I have checked releases, and the bug exists in the latest patch version of `v1` or `v2`.
- [x] `v2`
- [ ] `v1`

**Runners**

- [x] GitHub Hosted
- [ ] Self Hosted

**Operating systems**

**PHP versions**

8.1

**To Reproduce**

```yaml
      - name: Setup PHP
        uses: shivammathur/setup-php@verbose
        with:
          php-version: 8.1
          tools: symfony-cli
        env:
          fail-fast: true
```
**Expected behavior**

**Screenshots/Logs**

```
Err:3 https://repo.symfony.com/apt  Packages
  Could not handshake: The TLS connection was non-properly terminated. [IP: 3.224.177.130 443]
Ign:4 https://repo.symfony.com/apt  Translation-en
Reading package lists...
E: Failed to fetch https://repo.symfony.com/apt/Packages  Could not handshake: The TLS connection was non-properly terminated. [IP: 3.224.177.130 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
**Additional context**

The docs of the Symfony CLI now points to cloudsmith.io, a cloud based artifact repository. I think the link to the repository needs to be updated?
**Are you willing to submit a PR?**

**Comment by shivammathur** [comment] 2022-08-17 09:56
They changed the source repository again.
Fixed in https://github.com/shivammathur/setup-php/commit/44d81f983056c06a11e04e43aa61bf7726912278
Fix will be in the next release.

**Comment by starred-gijs** [comment] 2022-08-17 10:03
Thanks for your very quick fix! 🙏

**Comment by jakubtobiasz** [comment] 2022-08-17 10:06
@shivammathur thank you for quick fix 👏🏼🎉. Are you able to tell us estimated release date? This "bug" put down my all GitHub actions and I don't know if it is worth to make a workaround.

**Comment by shivammathur** [comment] 2022-08-17 10:11
Running the regression tests now. I will do a release today once those are complete.

**Comment by Kocal** [comment] 2022-08-17 10:34
Thanks @shivammathur :)

**Comment by shivammathur** [comment] 2022-08-17 11:51
Released [2.21.2](https://github.com/shivammathur/setup-php/releases/tag/2.21.2) with the fix.

**Closed by shivammathur** 2022-08-17 11:51 UTC
Labels: bug, awaiting-release

**Comment by bbredewold** [comment] 2022-08-17 12:32
Since this release my github actions have some problems. Do you think it has to do with some caching? 
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2910910/185123660-9461137f-02fa-4ba4-8d14-5500bb593c51.png">

**Comment by shivammathur** [comment] 2022-08-17 12:43
@bbredewold Please open a new issue with the details. If you specify `deployer` in `tools` input, it should be available.

**Comment by starred-gijs** [comment] 2022-08-17 13:12
I can confirm this issue is resolved! Again many thanks for the quick fix!
